export const countries = [
  { value: "AF", text: "Afghanistan" },
  { value: "AL", text: "Albania" },
  { value: "DZ", text: "Algeria" },
  { value: "AO", text: "Angola" },
  { value: "AR", text: "Argentina" },
  { value: "AU", text: "Australia" },
  { value: "AT", text: "Austria" },
  { value: "BD", text: "Bangladesh" },
  { value: "BE", text: "Belgium" },
  { value: "BJ", text: "Benin" },
  { value: "BW", text: "Botswana" },
  { value: "BR", text: "Brazil" },
  { value: "BG", text: "Bulgaria" },
  { value: "BF", text: "Burkina Faso" },
  { value: "BI", text: "Burundi" },
  { value: "CM", text: "Cameroon" },
  { value: "CA", text: "Canada" },
  { value: "TD", text: "Chad" },
  { value: "CN", text: "China" },
  { value: "CO", text: "Colombia" },
  { value: "CD", text: "Congo (DRC)" },
  { value: "CG", text: "Congo (Republic)" },
  { value: "CI", text: "Côte d’Ivoire" },
  { value: "DK", text: "Denmark" },
  { value: "EG", text: "Egypt" },
  { value: "ET", text: "Ethiopia" },
  { value: "FI", text: "Finland" },
  { value: "FR", text: "France" },
  { value: "GA", text: "Gabon" },
  { value: "DE", text: "Germany" },
  { value: "GH", text: "Ghana" },
  { value: "GR", text: "Greece" },
  { value: "IN", text: "India" },
  { value: "IE", text: "Ireland" },
  { value: "IL", text: "Israel" },
  { value: "IT", text: "Italy" },
  { value: "JP", text: "Japan" },
  { value: "KE", text: "Kenya" },
  { value: "MA", text: "Morocco" },
  { value: "NL", text: "Netherlands" },
  { value: "NG", text: "Nigeria" },
  { value: "NO", text: "Norway" },
  { value: "PL", text: "Poland" },
  { value: "PT", text: "Portugal" },
  { value: "RW", text: "Rwanda" },
  { value: "SN", text: "Senegal" },
  { value: "ZA", text: "South Africa" },
  { value: "SS", text: "South Sudan" },
  { value: "ES", text: "Spain" },
  { value: "SE", text: "Sweden" },
  { value: "CH", text: "Switzerland" },
  { value: "TZ", text: "Tanzania" },
  { value: "TN", text: "Tunisia" },
  { value: "UG", text: "Uganda" },
  { value: "GB", text: "United Kingdom" },
  { value: "US", text: "United States" },
  { value: "ZM", text: "Zambia" },
  { value: "ZW", text: "Zimbabwe" }
];
